common: &common
  adapter: postgresql
  username: rudash
  password: rudash
  host: 127.0.0.1

development:
  <<: *common
  database: rudash_development

test:
  <<: *common
  database: rudash_test

production:
  <<: *common
  database: rudash_production
